import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

PLUGIN_DIRNAME = "plugins"
PLUGIN_COLLECTORS_DIRNAME = "collectors"

PLUGIN_DIR = os.path.join(ROOT_DIR, PLUGIN_DIRNAME)

PLUGIN_COLLECTORS_DIR = os.path.join(PLUGIN_DIR, PLUGIN_COLLECTORS_DIRNAME)
PLUGIN_PARSERS_DIR = os.path.join(PLUGIN_DIR, "parsers")

ICONS_DIR = os.path.join(ROOT_DIR, "icons")


PLUGIN_COLLECTORS_OUTPUT_DIRNAME = "raw"
PLUGIN_COLLECTORS_PARSED_DIRNAME = "parsed"
PLUGIN_COLLECTORS_COMPRESSED_DIRNAME = "compressed"
PLUGIN_COLLECTORS_METADATA_DIRNAME = "META"

PLUGIN_COLLECTORS_CONFIG_FILENAME = "config.json"
PLUGIN_COLLECTORS_CONFIG_SCHEMA_FILENAME = "config_schema.json"

PLUGIN_COLLECTORS_METADATA_FILENAME_EXTENSION = ".txt"

PLUGIN_DISABLED_FILENAME = ".disabled"

TIMESTAMP_PLACEHOLDER = "%TIME%"

PLUGIN_COLLECTORS_EXPORT_DIRNAME = "ecel-export" + TIMESTAMP_PLACEHOLDER

PLUGIN_COLLECTORS_METADATA_FILE_COMMAND_PREFIX = "# "

PLUGIN_COLLECTORS_CONFIG_MULTI_OPTION_DELIMITER = ","
PLUGIN_COLLECTORS_CONFIG_MULTI_OPTION_DELIMITER_REGEX = PLUGIN_COLLECTORS_CONFIG_MULTI_OPTION_DELIMITER + "\s*"

ECEL_PARSER_ROOT="/root/Desktop/ecel-model/ecel_parser/"

ECEL_DSS_ROOT="/root/Desktop/ecel-model/dss/"
